name: release-please
on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            -   uses: google-github-actions/release-please-action@v3
                id: release
                with:
                    release-type: simple
                    extra-files: build.gradle.kts
                    include-v-in-tag: false
            -   uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
                # these if statements ensure that a publication only occurs when
                # a new release is created:
                if: ${{ steps.release.outputs.release_created }}
            # Build jar
            -   name: Set up JDK 17
                if: ${{ steps.release.outputs.release_created }}
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle
            -   name: Run chmod to make gradlew executable
                if: ${{ steps.release.outputs.release_created }}
                run: chmod +x ./gradlew
            -   name: Build with Gradle
                if: ${{ steps.release.outputs.release_created }}
                uses: gradle/gradle-build-action@62cce3c597efd445cd71ee868887b8b1117703a7
                with:
                    arguments: build
            -   name: Upload Release Artifact
                if: ${{ steps.release.outputs.release_created }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    gh release upload ${{ steps.release.outputs.tag_name }} build/libs/McDeob*.jar